apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    uid: {{.UID}}
spec:
  selector:
    uid: {{.PodUID}}
  ports:
  - port: {{.Port}}
    targetPort: {{.TargetPort}}
  type: {{.ServiceType}}